Repository PHP-FFMpeg/PHP-FFMpeg, pull requests merged in 2018-05, with the labels that each got.

#495 allow to set frame file type instead of hardcoded jpg
  src/FFMpeg/Filters/Video/ExtractMultipleFramesFilter.php
  tests/Unit/Filters/Video/ExtractMultipleFramesFilterTest.php
Labels: Feature

#524 Feature/videos from image
  src/FFMpeg/Filters/Audio/AudioFilters.php
  src/FFMpeg/Filters/Audio/ImageVideoFilter.php
  tests/Unit/Filters/Audio/AudioImageVideoFilterTest.php
Labels: Feature, needs testing, work-in-progress

#534 fix a bug when calling Frame->save()
  src/FFMpeg/Media/Frame.php
  tests/Unit/Media/FrameTest.php
Labels: bug
